spring:
  datasource:
    name: ${datasource.name}
    url: jdbc:mysql://${datasource.ip_port}/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8
    username: ${datasource.username}
    password: ${datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: ${datasource.maxActive}
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  # mybatis配置文件所在路径
  config-location: classpath:mybatis-config.xml
  # 所有的mapper映射文件
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  # 定义所有操作类的别名所在包
  type-aliases-package: cn.pukkasoft.datasync.model
#日志
logging:
  config: classpath:logback-spring.xml

#开启健康检查
#eureka:
#  client:
#    healthcheck:
#      enabled: true

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 5000

### xxl-job executor address
xxl.job.executor.appname: ${spring.application.name}
xxl.job.executor.ip:
xxl.job.executor.port: ${current.executor.port}

### xxl-job, access token
xxl.job.accessToken:

### xxl-job log path
xxl.job.executor.logpath: /log/${spring.application.name}/jobhandler
### xxl-job log retention days
xxl.job.executor.logretentiondays: 30


contentInfo:
  url: http://111.11.189.150:8081/
  path: IPTVPortalInterface/content/getcontentlist.do
  portalCode: PCODE-t2gwbgzp
  spToken: 4F673775CD9E51276730A9E8EA7EA9D2
  spId: 1005

canal:
  destination: example
  host: 172.25.86.73
  port: 11111
  table: ottdb_gsgd.t_contentinfo
  batchSize: 1000
  waitTime: 400