#datasource
datasource:
  ip_port: 192.168.2.43:3306
  username: root
  password: 123456

#redis
redis:
  host: 192.168.2.84
  port: 6379
  password: 123456
#redis db
spring.redis.database: 2

#nats
nats:
  threadcount: 10
  address: nats://192.168.2.42:4222,nats://192.168.2.84:4222
  topic:
    iptv:
      log:
        history: nats.iptv.log.history
        realtime: nats.iptv.log.realtime
      recommend:
        snapshot: nats.iptv.recommend.snapshot
#security
security:
  username: admin
  password: 123456

#swagger api域名
swagger.host: localhost:8005


elasticsearch:
  urls: 192.168.2.44,192.168.2.63,192.168.2.84