#请求关键字黑白名单
uri.white: /swagger-resources,/v2/api-docs,/n/
uri.black:
#redis
redis.pool.max-active: 500
#zuul
zuul.host.maxTotalConnections: 2000
zuul.host.maxPerRouteConnections: 200
zuul.semaphore.max-semaphores: 1000
#jwt
jwt.secret-key: u2b3o4c8a6r9e273f6com46ffd57
